//Util file, used to store all the genres and their corresponding IDs in the tMDB API.

export const genreIDs = {
    "10759": "Action & Adventure",
    "16": "Animation",
    "35": "Comedy",
    "80": "Crime",
    "99": "Documentary",
    "18": "Drama",
    "10751": "Family",
    "10762": "Kids",
    "9648": "Mystery",
    "10763": "News",
    "10764": "Reality",
    "10765": "Sci-Fi & Fantasy",
    "10766": "Soap",
    "10767": "Talk",
    "10768": "War & Politics",
    "37": "Western",
    "28": "Action",
    "12": "Adventure",
    "14": "Fantasy",
    "36": "History",
    "27": "Horror",
    "10402": "Music",
    "10749": "Romance",
    "878": "Science Fiction",
    "10770": "TV Movie",
    "53": "Thriller"
  }

  export const tvGenres = {
    "Action & Adventure": 10759,
    "Animation": 16,
    "Comedy": 35,
    "Crime": 80,
    "Documentary": 99,
    "Drama": 18,
    "Family": 10751,
    "Kids": 10762,
    "Mystery": 9648,
    "News": 10763,
    "Reality": 10764,
    "Sci-Fi & Fantasy": 10765,
    "Soap": 10766,
    "Talk": 10767,
    "War & Politics": 10768,
    "Western": 37
  }
export const movieGenres = {
  "Action": 28,
  "Adventure": 12,
  "Animation": 16,
  "Comedy": 35,
  "Crime": 80,
  "Documentary": 99,
  "Drama": 18,
  "Family": 10751,
  "Fantasy": 14,
  "History": 36,
  "Horror": 27,
  "Music": 10402,
  "Mystery": 9648,
  "Romance": 10749,
  "Science Fiction": 878,
  "TV Movie": 10770,
  "Thriller": 53,
  "War": 10752,
  "Western": 37
}
  export const movieGenreDropdown = [
    {value: "Action", label: "Action"},
    {value: "Adventure", label: "Adventure"},
    {value: "Animation", label: "Animation"},
    {value: "Comedy", label: "Comedy"},
    {value: "Crime", label: "Crime"},
    {value: "Documentary", label: "Documentary"},
    {value: "Drama", label: "Drama"},
    {value: "Family", label: "Family"},
    {value: "Fantasy", label: "Fantasy"},
    {value: "History", label: "History"},
    {value: "Horror", label: "Horror"},
    {value: "Music", label: "Music"},
    {value: "Mystery", label: "Mystery"},
    {value: "Romance", label: "Romance"},
    {value: "Science Fiction", label: "Science Fiction"},
    {value: "Thriller", label: "Thriller"},
    {value: "War", label: "War"},
    {value: "Western", label: "Western"}
  ]
  export const tvGenreDropdown = [
    {value: "Action & Adventure", label: "Action & Adventure"},
    {value: "Animation", label: "Animation"},
    {value: "Comedy", label: "Comedy"},
    {value: "Crime", label: "Crime"},
    {value: "Documentary", label: "Documentary"},
    {value: "Drama", label: "Drama"},
    {value: "Family", label: "Family"},
    {value: "Kids", label: "Kids"},
    {value: "Mystery", label: "Mystery"},
    {value: "News", label: "News"},
    {value: "Reality", label: "Reality"},
    {value: "Sci-Fi & Fantasy", label: "Sci-Fi & Fantasy"},
    {value: "Soap", label: "Soap"},
    {value: "Talk", label: "Talk"},
    {value: "War & Politics", label: "War & Politics"},
    {value: "Western", label: "Western"}
  ]
